/**
 * FarmConnect - Realistic Agricultural Mock Datasets
 */

const INITIAL_DEMO_USERS = {
  farmer: {
    id: "usr_farmer_01",
    role: "farmer",
    name: "Rameshwar Patil",
    email: "farmer@farmconnect.com",
    phone: "+91 98234 56789",
    avatar: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=200&auto=format&fit=crop&q=80",
    farmName: "Patil Organic Agri Farms",
    location: "Nashik, Maharashtra",
    distance: "18 km away",
    rating: 4.9,
    totalRatings: 128,
    isVerified: true,
    kisanCardNumber: "MH-NSK-2024-8841",
    experienceYears: 16,
    totalCropsSold: "1,420 Quintals",
    bankDetails: {
      accountHolder: "Rameshwar B. Patil",
      bankName: "State Bank of India",
      accountNumber: "•••• •••• 4892",
      ifsc: "SBIN0001244",
      upiId: "patil.farm@sbi"
    },
    bio: "Passionate certified organic farmer producing export-grade tomatoes, onions, and table grapes using sustainable drip irrigation and zero chemical pesticides."
  },
  buyer: {
    id: "usr_buyer_01",
    role: "buyer",
    name: "Ananya Sharma",
    email: "buyer@farmconnect.com",
    phone: "+91 97112 34567",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80",
    buyerType: "Retail Consumer & Organic Enthusiast",
    location: "Kothrud, Pune, Maharashtra",
    deliveryAddress: {
      fullName: "Ananya Sharma",
      phone: "+91 97112 34567",
      street: "Flat 402, Green Meadows Residency, Paud Road",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411038",
      landmark: "Near Vanaz Metro Station"
    }
  }
};

const INITIAL_PRODUCTS = [
  {
    id: "prod_01",
    name: "Fresh Hybrid Red Tomatoes",
    category: "Vegetables",
    price: 34,
    unit: "kg",
    minOrderQty: 5,
    availableQty: 450,
    harvestDate: "2026-08-19",
    freshness: "Harvested Yesterday",
    isOrganic: true,
    organicCert: "NPOP Organic India Certified",
    farmerId: "usr_farmer_01",
    farmerName: "Rameshwar Patil",
    farmName: "Patil Organic Agri Farms",
    location: "Nashik, Maharashtra",
    rating: 4.9,
    reviewsCount: 46,
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80",
    description: "Vine-ripened, naturally sweet and firm hybrid tomatoes grown with zero synthetic pesticides. Ideal for household cooking, restaurants, and paste making.",
    shelfLifeDays: 8,
    bulkDiscount: "10% off for 50kg+"
  },
  {
    id: "prod_02",
    name: "Nashik Premium Red Onions",
    category: "Vegetables",
    price: 28,
    unit: "kg",
    minOrderQty: 10,
    availableQty: 1200,
    harvestDate: "2026-08-17",
    freshness: "Cured & Graded 4 Days Ago",
    isOrganic: false,
    organicCert: "Standard APMC Graded A+",
    farmerId: "usr_farmer_01",
    farmerName: "Rameshwar Patil",
    farmName: "Patil Organic Agri Farms",
    location: "Lasalgaon, Nashik",
    rating: 4.8,
    reviewsCount: 84,
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&auto=format&fit=crop&q=80",
    description: "Export quality Lasalgaon pinkish-red onions. High pungency, thick skin, excellent keeping quality for long storage.",
    shelfLifeDays: 30,
    bulkDiscount: "₹2/kg discount on 100kg+"
  },
  {
    id: "prod_03",
    name: "Jyoti Golden Table Potatoes",
    category: "Vegetables",
    price: 22,
    unit: "kg",
    minOrderQty: 5,
    availableQty: 850,
    harvestDate: "2026-08-15",
    freshness: "Direct from Cold Farm Vault",
    isOrganic: true,
    organicCert: "Jaivik Bharat Certified",
    farmerId: "usr_farmer_02",
    farmerName: "Suresh Deshmukh",
    farmName: "Deshmukh Agro Land",
    location: "Manchar, Pune",
    rating: 4.7,
    reviewsCount: 32,
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80",
    description: "Crisp and smooth-skinned Kufri Jyoti potatoes. Rich in starch, perfect for baking, frying, and everyday curries.",
    shelfLifeDays: 45,
    bulkDiscount: "8% off on 50kg+"
  },
  {
    id: "prod_04",
    name: "Sharbati Golden Wheat (Unpolished)",
    category: "Grains & Cereals",
    price: 46,
    unit: "kg",
    minOrderQty: 25,
    availableQty: 3200,
    harvestDate: "2026-07-28",
    freshness: "Sun-dried & Machine Cleaned",
    isOrganic: true,
    organicCert: "Jaivik Bharat Certified",
    farmerId: "usr_farmer_03",
    farmerName: "Balwinder Singh",
    farmName: "Singh Natural Harvests",
    location: "Sehore, Madhya Pradesh",
    rating: 4.95,
    reviewsCount: 92,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80",
    description: "Aromatic, golden-kernelled Sharbati MP wheat known as the 'Queen of Wheat'. Makes extremely soft, sweet, and fluffy rotis with rich dietary fiber.",
    shelfLifeDays: 180,
    bulkDiscount: "₹3/kg off on 1 Quintal (100kg)"
  },
  {
    id: "prod_05",
    name: "Traditional Basmati Paddy Rice (Taraori)",
    category: "Grains & Cereals",
    price: 78,
    unit: "kg",
    minOrderQty: 10,
    availableQty: 2100,
    harvestDate: "2026-07-10",
    freshness: "Aged 1 Year for Maximum Flavour",
    isOrganic: true,
    organicCert: "NPOP Organic India",
    farmerId: "usr_farmer_04",
    farmerName: "Harpreet Brar",
    farmName: "Doaba Green Acres",
    location: "Karnal, Haryana",
    rating: 4.9,
    reviewsCount: 54,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80",
    description: "Authentic long-grain scented Basmati rice. When cooked, grains elongate up to 2.5x without sticking. Direct farm price eliminates 4 intermediate mill charges.",
    shelfLifeDays: 365,
    bulkDiscount: "12% off on 100kg+"
  },
  {
    id: "prod_06",
    name: "Fresh Juicy Crunchy Red Carrots",
    category: "Vegetables",
    price: 36,
    unit: "kg",
    minOrderQty: 3,
    availableQty: 380,
    harvestDate: "2026-08-20",
    freshness: "Harvested Today Morning",
    isOrganic: true,
    organicCert: "NPOP Organic India",
    farmerId: "usr_farmer_01",
    farmerName: "Rameshwar Patil",
    farmName: "Patil Organic Agri Farms",
    location: "Nashik, Maharashtra",
    rating: 4.8,
    reviewsCount: 29,
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&auto=format&fit=crop&q=80",
    description: "Sweet, crunchy, washed country carrots packed with Vitamin A and natural carotenoids. Great for fresh juicing, salads, and carrot halwa.",
    shelfLifeDays: 10,
    bulkDiscount: "5% off for 20kg+"
  },
  {
    id: "prod_07",
    name: "Grand Naine Ripe Yellow Bananas",
    category: "Fruits",
    price: 42,
    unit: "dozen",
    minOrderQty: 2,
    availableQty: 260,
    harvestDate: "2026-08-19",
    freshness: "Naturally Ethylene Ripened (Zero Carbide)",
    isOrganic: true,
    organicCert: "Certified Chemical-Free",
    farmerId: "usr_farmer_05",
    farmerName: "Kishor Chaudhari",
    farmName: "Khandesh Banana Orchards",
    location: "Jalgaon, Maharashtra",
    rating: 4.85,
    reviewsCount: 68,
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop&q=80",
    description: "Creamy, naturally sweet Jalgaon G-9 bananas ripened naturally in temperature-controlled chambers without harmful carbide chemicals.",
    shelfLifeDays: 6,
    bulkDiscount: "₹5/dozen off on 10+ dozens"
  },
  {
    id: "prod_08",
    name: "Ratnagiri Alphonso (Hapus) Mangoes",
    category: "Fruits",
    price: 580,
    unit: "dozen",
    minOrderQty: 1,
    availableQty: 85,
    harvestDate: "2026-08-18",
    freshness: "GI Tag Certified Batch",
    isOrganic: true,
    organicCert: "Geographical Indication (GI) Registered",
    farmerId: "usr_farmer_06",
    farmerName: "Ganesh Kelkar",
    farmName: "Konkan Heritage Orchards",
    location: "Devgad, Ratnagiri",
    rating: 5.0,
    reviewsCount: 112,
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&auto=format&fit=crop&q=80",
    description: "The King of Mangoes! Authentic Devgad Alphonso with distinct floral aroma, golden saffron pulp, and silky fibreless texture.",
    shelfLifeDays: 7,
    bulkDiscount: "10% off on 5+ Crates"
  },
  {
    id: "prod_09",
    name: "Organic Farm Raw Honey (Wildflower)",
    category: "Dairy & Organic",
    price: 340,
    unit: "kg",
    minOrderQty: 1,
    availableQty: 140,
    harvestDate: "2026-08-01",
    freshness: "Raw & Unprocessed",
    isOrganic: true,
    organicCert: "Jaivik Bharat Certified",
    farmerId: "usr_farmer_07",
    farmerName: "Mahesh Joshi",
    farmName: "Sahyadri Bee Apiary",
    location: "Mahabaleshwar, Maharashtra",
    rating: 4.9,
    reviewsCount: 38,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80",
    description: "100% pure raw wildflower honey extracted from bee boxes stationed in western ghat forest ranges. Unpasteurized and packed with natural pollen enzymes.",
    shelfLifeDays: 500,
    bulkDiscount: "₹30 off on 3kg+"
  },
  {
    id: "prod_10",
    name: "Salem Lakadong High-Curcumin Turmeric",
    category: "Spices & Herbs",
    price: 180,
    unit: "kg",
    minOrderQty: 1,
    availableQty: 320,
    harvestDate: "2026-07-25",
    freshness: "Hand-sorted Dry Fingers",
    isOrganic: true,
    organicCert: "Jaivik Bharat Organic",
    farmerId: "usr_farmer_08",
    farmerName: "Venkatesan Pillai",
    farmName: "Kaveri Spice Estates",
    location: "Salem, Tamil Nadu",
    rating: 4.92,
    reviewsCount: 45,
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80",
    description: "Potent yellow turmeric rhizomes containing over 5.8% natural curcumin content. Ideal for medicinal use, herbal immunity tonics, and culinary spice blends.",
    shelfLifeDays: 360,
    bulkDiscount: "15% off on 10kg+"
  },
  {
    id: "prod_11",
    name: "Crisp Green Capsicum (Bell Pepper)",
    category: "Vegetables",
    price: 48,
    unit: "kg",
    minOrderQty: 2,
    availableQty: 210,
    harvestDate: "2026-08-20",
    freshness: "Polyhouse Fresh Pick",
    isOrganic: true,
    organicCert: "Hydro-Green Certified",
    farmerId: "usr_farmer_01",
    farmerName: "Rameshwar Patil",
    farmName: "Patil Organic Agri Farms",
    location: "Nashik, Maharashtra",
    rating: 4.75,
    reviewsCount: 22,
    image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&auto=format&fit=crop&q=80",
    description: "Thick-walled, vibrant green bell peppers harvested from greenhouse beds. Crisp texture and juicy crunch with low moisture loss.",
    shelfLifeDays: 9,
    bulkDiscount: "5% off for 15kg+"
  },
  {
    id: "prod_12",
    name: "Desi Gir Cow A2 Raw Milk (Chilled)",
    category: "Dairy & Organic",
    price: 75,
    unit: "liter",
    minOrderQty: 2,
    availableQty: 110,
    harvestDate: "2026-08-21",
    freshness: "Milked Today 5:00 AM",
    isOrganic: true,
    organicCert: "100% Pure Desi Gir Breed",
    farmerId: "usr_farmer_02",
    farmerName: "Suresh Deshmukh",
    farmName: "Deshmukh Agro Land",
    location: "Manchar, Pune",
    rating: 4.95,
    reviewsCount: 76,
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80",
    description: "Pure whole A2 beta-casein milk from grass-fed Desi Gir cows. Chilled immediately to 4°C for farm-fresh doorstep delivery in sterile glass bottles.",
    shelfLifeDays: 2,
    bulkDiscount: "₹5/liter off on monthly subscription"
  }
];

const INITIAL_MANDI_PRICES = [
  {
    id: "mandi_01",
    commodity: "Tomato (Hybrid)",
    category: "Vegetables",
    currentPrice: 34,
    previousPrice: 30,
    changePercent: 13.3,
    trend: "up",
    localMandi: "Pimpalgaon APMC (₹3,200/Q)",
    bestMandi: "Azadpur APMC, Delhi (₹3,600/Q)",
    farmConnectPrice: 34,
    marketDemand: "High Demand",
    demandColor: "text-emerald-700 bg-emerald-100",
    advisoryTip: "Harvest peak flush now; urban demand has jumped 18% over the past 48 hours."
  },
  {
    id: "mandi_02",
    commodity: "Red Onion (Nashik Quality)",
    category: "Vegetables",
    currentPrice: 28,
    previousPrice: 29.5,
    changePercent: -5.1,
    trend: "down",
    localMandi: "Lasalgaon APMC (₹2,650/Q)",
    bestMandi: "Vashi APMC, Mumbai (₹2,950/Q)",
    farmConnectPrice: 28,
    marketDemand: "Steady",
    demandColor: "text-blue-700 bg-blue-100",
    advisoryTip: "Store well-cured bulbs in aerated crates. Prices projected to stabilize next week."
  },
  {
    id: "mandi_03",
    commodity: "Potato (Kufri Jyoti)",
    category: "Vegetables",
    currentPrice: 22,
    previousPrice: 21,
    changePercent: 4.8,
    trend: "up",
    localMandi: "Pune Market Yard (₹2,100/Q)",
    bestMandi: "Agra Mandi, UP (₹2,350/Q)",
    farmConnectPrice: 22,
    marketDemand: "High Demand",
    demandColor: "text-emerald-700 bg-emerald-100",
    advisoryTip: "Direct retail through FarmConnect yields ₹4/kg more than middlemen commissions."
  },
  {
    id: "mandi_04",
    commodity: "Sharbati Wheat (Grade A)",
    category: "Grains & Cereals",
    currentPrice: 46,
    previousPrice: 44,
    changePercent: 4.5,
    trend: "up",
    localMandi: "Sehore APMC (₹4,200/Q)",
    bestMandi: "Khanna Mandi, Punjab (₹4,700/Q)",
    farmConnectPrice: 46,
    marketDemand: "Very High",
    demandColor: "text-purple-700 bg-purple-100",
    advisoryTip: "Premium grain quality commanding strong buyer interest for residential bulk bags."
  },
  {
    id: "mandi_05",
    commodity: "Basmati Rice (Aged Grain)",
    category: "Grains & Cereals",
    currentPrice: 78,
    previousPrice: 76,
    changePercent: 2.6,
    trend: "up",
    localMandi: "Karnal APMC (₹7,200/Q)",
    bestMandi: "Delhi APMC (₹8,100/Q)",
    farmConnectPrice: 78,
    marketDemand: "Export Rally",
    demandColor: "text-indigo-700 bg-indigo-100",
    advisoryTip: "Zero packaging deductions when listing directly to cooperative buyer groups."
  },
  {
    id: "mandi_06",
    commodity: "Grand Naine Banana",
    category: "Fruits",
    currentPrice: 42,
    previousPrice: 45,
    changePercent: -6.6,
    trend: "down",
    localMandi: "Jalgaon Mandi (₹1,600/Crate)",
    bestMandi: "Surat APMC (₹1,850/Crate)",
    farmConnectPrice: 42,
    marketDemand: "Moderate",
    demandColor: "text-amber-700 bg-amber-100",
    advisoryTip: "Bundle as ripe ready-to-eat packs to capture premium household buyers."
  },
  {
    id: "mandi_07",
    commodity: "Lakadong Turmeric",
    category: "Spices & Herbs",
    currentPrice: 180,
    previousPrice: 168,
    changePercent: 7.1,
    trend: "up",
    localMandi: "Erode APMC (₹16,500/Q)",
    bestMandi: "Sangli Mandi (₹18,200/Q)",
    farmConnectPrice: 180,
    marketDemand: "Surging",
    demandColor: "text-emerald-700 bg-emerald-100",
    advisoryTip: "High curcumin varieties in peak demand for wellness and Ayurvedic products."
  },
  {
    id: "mandi_08",
    commodity: "Green Bell Pepper (Capsicum)",
    category: "Vegetables",
    currentPrice: 48,
    previousPrice: 42,
    changePercent: 14.2,
    trend: "up",
    localMandi: "Nashik APMC (₹4,400/Q)",
    bestMandi: "Vashi APMC (₹5,200/Q)",
    farmConnectPrice: 48,
    marketDemand: "Peak Season",
    demandColor: "text-emerald-700 bg-emerald-100",
    advisoryTip: "Hotel and restaurant buyers are seeking regular weekly contracts."
  }
];

const INITIAL_ORDERS = [
  {
    id: "ORD-94821",
    date: "2026-08-21 08:30 AM",
    expectedDelivery: "2026-08-22 (Within 24 Hours)",
    buyerId: "usr_buyer_01",
    buyerName: "Ananya Sharma",
    buyerPhone: "+91 97112 34567",
    deliveryAddress: "Flat 402, Green Meadows Residency, Paud Road, Pune 411038",
    farmerId: "usr_farmer_01",
    farmerName: "Rameshwar Patil",
    farmName: "Patil Organic Agri Farms",
    farmerPhone: "+91 98234 56789",
    items: [
      {
        productId: "prod_01",
        name: "Fresh Hybrid Red Tomatoes",
        price: 34,
        unit: "kg",
        quantity: 10,
        image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80"
      },
      {
        productId: "prod_06",
        name: "Fresh Juicy Crunchy Red Carrots",
        price: 36,
        unit: "kg",
        quantity: 5,
        image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&auto=format&fit=crop&q=80"
      }
    ],
    itemTotal: 520,
    deliveryFee: 0,
    discount: 52,
    total: 468,
    paymentMethod: "UPI (Google Pay)",
    paymentStatus: "Paid",
    status: "Pending", // Statuses: Pending, Confirmed, Shipped, Out for Delivery, Delivered, Cancelled
    trackingTimeline: [
      { step: "Order Placed", time: "Aug 21, 08:30 AM", completed: true, desc: "Order received and payment verified via UPI." },
      { step: "Confirmed", time: "Pending confirmation", completed: false, desc: "Farmer will confirm produce stock & packing." },
      { step: "Shipped", time: "Pending", completed: false, desc: "Picked up by AgriLogistics Van from Nashik Farm." },
      { step: "Out for Delivery", time: "Pending", completed: false, desc: "Delivery executive en route to Kothrud, Pune." },
      { step: "Delivered", time: "Pending", completed: false, desc: "Fresh produce received at doorstep." }
    ],
    deliveryPartner: {
      name: "Vikas Shinde",
      vehicle: "AgriDirect Express Van (MH-15-EG-4912)",
      phone: "+91 98450 11223"
    }
  },
  {
    id: "ORD-94610",
    date: "2026-08-20 02:15 PM",
    expectedDelivery: "2026-08-21 (Today by 4:00 PM)",
    buyerId: "usr_buyer_01",
    buyerName: "Ananya Sharma",
    buyerPhone: "+91 97112 34567",
    deliveryAddress: "Flat 402, Green Meadows Residency, Paud Road, Pune 411038",
    farmerId: "usr_farmer_01",
    farmerName: "Rameshwar Patil",
    farmName: "Patil Organic Agri Farms",
    farmerPhone: "+91 98234 56789",
    items: [
      {
        productId: "prod_02",
        name: "Nashik Premium Red Onions",
        price: 28,
        unit: "kg",
        quantity: 25,
        image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&auto=format&fit=crop&q=80"
      }
    ],
    itemTotal: 700,
    deliveryFee: 40,
    discount: 0,
    total: 740,
    paymentMethod: "Cash on Delivery",
    paymentStatus: "Pending on Delivery",
    status: "Out for Delivery",
    trackingTimeline: [
      { step: "Order Placed", time: "Aug 20, 02:15 PM", completed: true, desc: "Order booked by buyer." },
      { step: "Confirmed", time: "Aug 20, 03:00 PM", completed: true, desc: "Stock packed & sealed by Patil Organic Farm." },
      { step: "Shipped", time: "Aug 20, 07:45 PM", completed: true, desc: "Dispatched via refrigerated transport." },
      { step: "Out for Delivery", time: "Aug 21, 09:15 AM", completed: true, desc: "Driver out for local delivery in Pune." },
      { step: "Delivered", time: "Estimated 04:00 PM", completed: false, desc: "Final handover at doorstep." }
    ],
    deliveryPartner: {
      name: "Sachin Gaikwad",
      vehicle: "Kisan Express EV Cargo (MH-12-QC-8821)",
      phone: "+91 98901 22334"
    }
  },
  {
    id: "ORD-93502",
    date: "2026-08-17 11:00 AM",
    expectedDelivery: "2026-08-18",
    buyerId: "usr_buyer_01",
    buyerName: "Ananya Sharma",
    buyerPhone: "+91 97112 34567",
    deliveryAddress: "Flat 402, Green Meadows Residency, Paud Road, Pune 411038",
    farmerId: "usr_farmer_06",
    farmerName: "Ganesh Kelkar",
    farmName: "Konkan Heritage Orchards",
    farmerPhone: "+91 98111 22446",
    items: [
      {
        productId: "prod_08",
        name: "Ratnagiri Alphonso (Hapus) Mangoes",
        price: 580,
        unit: "dozen",
        quantity: 2,
        image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&auto=format&fit=crop&q=80"
      }
    ],
    itemTotal: 1160,
    deliveryFee: 0,
    discount: 100,
    total: 1060,
    paymentMethod: "UPI (PhonePe)",
    paymentStatus: "Paid & Settled",
    status: "Delivered",
    trackingTimeline: [
      { step: "Order Placed", time: "Aug 17, 11:00 AM", completed: true, desc: "Order confirmed." },
      { step: "Confirmed", time: "Aug 17, 12:30 PM", completed: true, desc: "Specially packed in cushioned wooden crate." },
      { step: "Shipped", time: "Aug 17, 05:00 PM", completed: true, desc: "Dispatched from Devgad orchard." },
      { step: "Out for Delivery", time: "Aug 18, 08:30 AM", completed: true, desc: "Courier out for delivery." },
      { step: "Delivered", time: "Aug 18, 01:20 PM", completed: true, desc: "Package successfully delivered to buyer." }
    ],
    deliveryPartner: {
      name: "Santosh Mane",
      vehicle: "Konkan Express Courier (MH-08-AB-1290)",
      phone: "+91 94220 77889"
    }
  }
];

const INITIAL_CONVERSATIONS = [
  {
    id: "conv_01",
    farmerId: "usr_farmer_01",
    farmerName: "Rameshwar Patil",
    farmerAvatar: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=200&auto=format&fit=crop&q=80",
    farmName: "Patil Organic Agri Farms",
    buyerId: "usr_buyer_01",
    buyerName: "Ananya Sharma",
    productId: "prod_01",
    productName: "Fresh Hybrid Red Tomatoes",
    productPrice: "₹34/kg",
    lastUpdated: "10:15 AM",
    unreadCount: 1,
    messages: [
      {
        id: "msg_1",
        sender: "buyer",
        text: "Namaste Rameshwar ji! I saw your fresh tomato listing. Are they 100% organic without any chemical spray?",
        time: "09:45 AM"
      },
      {
        id: "msg_2",
        sender: "farmer",
        text: "Namaste Ananya ji! Yes, completely natural. We use Jeevamrutha bio-fertilizer and neem oil decoction. Harvested freshly yesterday morning!",
        time: "09:50 AM"
      },
      {
        id: "msg_3",
        sender: "buyer",
        text: "That is wonderful! Can you deliver 10kg to Pune by tomorrow?",
        time: "10:10 AM"
      },
      {
        id: "msg_4",
        sender: "farmer",
        text: "Absolutely! Please place the order through the app and I will pack the finest grade batch for your family.",
        time: "10:15 AM"
      }
    ]
  }
];

const INITIAL_NOTIFICATIONS = [
  {
    id: "notif_01",
    type: "order",
    title: "New Direct Order Received! 🎉",
    message: "Buyer Ananya Sharma placed order #ORD-94821 for 10kg Tomatoes & 5kg Carrots (₹468).",
    time: "15 mins ago",
    isRead: false,
    target: "orders"
  },
  {
    id: "notif_02",
    type: "price",
    title: "Tomato Mandi Rate Alert 📈",
    message: "Tomato prices in Pimpalgaon Mandi increased by +13.3% today to ₹34/kg.",
    time: "1 hour ago",
    isRead: false,
    target: "mandi"
  },
  {
    id: "notif_03",
    type: "payment",
    title: "Payment Credited 💰",
    message: "₹1,060 settled for Order #ORD-93502 directly to your State Bank of India account.",
    time: "2 hours ago",
    isRead: true,
    target: "earnings"
  },
  {
    id: "notif_04",
    type: "message",
    title: "New Message from Buyer 💬",
    message: "Ananya Sharma inquired about bulk delivery for Tomatoes.",
    time: "3 hours ago",
    isRead: true,
    target: "chat"
  }
];
